set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)

set(CMAKE_AR            aarch64-none-linux-gnu-ar)
set(CMAKE_ASM_COMPILER  aarch64-none-linux-gnu-gcc)
set(CMAKE_C_COMPILER    aarch64-none-linux-gnu-gcc)
set(CMAKE_CXX_COMPILER  aarch64-none-linux-gnu-g++)
set(CMAKE_LINKER        aarch64-none-linux-gnu-ld)
set(CMAKE_OBJDUMP       aarch64-none-linux-gnu-objdump  CACHE INTERNAL "")
set(CMAKE_OBJCOPY       aarch64-none-linux-gnu-objcopy  CACHE INTERNAL "")
set(CMAKE_RANLIB        aarch64-none-linux-gnu-ranlib   CACHE INTERNAL "")
set(CMAKE_SIZE          aarch64-none-linux-gnu-size     CACHE INTERNAL "")
set(CMAKE_STRIP         aarch64-none-linux-gnu-strip    CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
